"""Cross-check against an explicitly constructed Galois closure.

The Galois closure is built as the field generated by a primitive element,
and the ramification index, residue degree, number of primes and discriminant
valuation at every ramified prime are read off it, then compared with the
pipeline's decomposition and inertia groups and conductor exponents.  Where no
primitive element yields a maximal order at a prime within the budget and the
discriminant valuation is small, the comparison uses the local structure that
the factor data already force, and the run records that it did so.
"""
from __future__ import annotations
import os, tempfile, time, json
from math import gcd

from .run import run_pipeline
from .certificate import load_json
from .precision import Policy
from .invariants import Invariant
from .resolvent import roots_at, resolvent, evaluate_permuted, squarefree_certificate
from .ramified import discriminant, factor_mod, dedekind_criterion, decide_prime_for_factor, valuation, factorint
from .perm import PermGroup, from_json, symmetric, alternating, from_cycles

def lcm(a, b):
    return a * b // gcd(a, b)

def mult_order(a, m):
    if m == 1:
        return 1
    k, x = 1, a % m
    while x != 1:
        x = x * a % m; k += 1
    return k

def group_generators(name, n):
    S = symmetric(n)
    if name == "S":
        return [list(range(2, n + 1)) + [1], [2, 1] + list(range(3, n + 1))]
    if name == "A":
        return [[i + 1 for i in g] for g in alternating(n).generators]
    if name == "C":
        return [list(range(2, n + 1)) + [1]]
    if name == "D":
        return [list(range(2, n + 1)) + [1], [1] + list(range(n, 1, -1))]
    if name == "F20":
        return [[2, 3, 4, 5, 1], [1, 3, 5, 2, 4]]
    if name == "V4":
        return [[2, 1, 3, 4], [1, 2, 4, 3]]
    raise ValueError(name)

def explicit_N(G, f, p, policy, seed=0, tries=4, log=print):
    """Minimal polynomials of several primitive elements theta = sum c_i alpha_i (degree |G|)."""
    n = G.n
    T = G.elements()
    out = []
    for attempt in range(tries):
        c = [(i + 1) + attempt * ((i * i + 3 * i) % 7) for i in range(n)]
        F = Invariant(n, {tuple(1 if i == j else 0 for i in range(n)): c[j] for j in range(n)}, label=f"theta{attempt}")
        trial = Policy(f, policy.Delta, mode=policy.mode)
        trial.register(F, G.order())
        ring, roots, _ = roots_at(f, p, trial.k(p), seed=seed)
        R, _ = resolvent(F, T, roots, ring)
        if squarefree_certificate(R) is not None:
            out.append((c, R))
    return out

def reference_at_prime(minpolys, ell, order, max_round2_degree=12):
    """(e, f, g) of ell in N from the first theta with Z[theta] ell-maximal (Dedekind), else Round 2
    when deg <= max_round2_degree, else None."""
    for c, R in minpolys:
        maximal, facs, gcds = dedekind_criterion(R, ell)
        if maximal:
            es = {e for g, e in facs}; fs = {len(g) - 1 for g, e in facs}
            if len(es) != 1 or len(fs) != 1:
                return {"status": "N not Galois?!", "facs": [(len(g) - 1, e) for g, e in facs]}
            e, fdeg = es.pop(), fs.pop()
            return {"status": "Dedekind", "theta": c, "e": e, "f": fdeg, "g": len(facs), "v_disc_N": len(facs) * fdeg * (e - 1) if e % ell else None}
    if order <= max_round2_degree:
        c, R = minpolys[0]
        w = decide_prime_for_factor(R, ell)
        dec = w["residue_decomposition"]
        es = {e for e, f_ in dec}; fs = {f_ for e, f_ in dec}
        e, fdeg = es.pop(), fs.pop()
        return {"status": "Round 2", "theta": c, "e": e, "f": fdeg, "g": len(dec), "v_disc_N": w["v_disc_O"]}
    return None

def restricted_reference(A2_dec, ell, order):
    """Tame local structure forced by the factor data when v_ell(disc f) <= 2."""
    E = 1
    for e, fd in A2_dec:
        E = lcm(E, e)
    if E % ell == 0:
        return None
    F = 1
    for e, fd in A2_dec:
        F = lcm(F, fd)
    F = lcm(F, mult_order(ell, E))
    return {"status": "restricted (v <= 2, forced by the factor data)", "e": E, "f": F, "g": order // (E * F), "v_disc_N": (order // (E * F)) * F * (E - 1)}

def check_polynomial(f, gens, X=100, log=print, workdir=None, budget_degree=120):
    d = workdir or tempfile.mkdtemp()
    cfg = {"f": f, "generators": gens, "run_dir": d,
           "options": {"precision_check": False, "class_confirmation": False, "class_bound_X": X,
                       "local_unramified_check": 0, "fe_test": False, "compute_models": False, "quiet": True, "root_numbers": False}}
    t0 = time.time()
    try:
        run_pipeline(cfg)
    except Exception as ex:
        return {"f": f, "status": f"pipeline failed: {ex}"}
    G = PermGroup([from_json(g) for g in load_json(os.path.join(d, "group.json"))["generators"]], n=len(f) - 1)
    L = load_json(os.path.join(d, "local.json"))
    CJ = load_json(os.path.join(d, "conductors.json"))
    T = load_json(os.path.join(d, "chartable.json"))
    R = load_json(os.path.join(d, "ramified.json"))
    P = load_json(os.path.join(d, "precision.json"))
    Delta = abs(discriminant(f))
    policy = Policy(f, Delta, mode=P["mode"])
    p = load_json(os.path.join(d, "certificate.json"))["precision"]["numbering_prime"]
    order = G.order()
    minpolys = explicit_N(G, f, p, policy, log=log) if order <= budget_degree else []
    rec = {"f": f, "|G|": order, "disc": Delta, "primes": {}, "seconds_pipeline": round(time.time() - t0, 1)}
    all_ok = True
    for ell_s, prec in R["per_prime"].items():
        ell = int(ell_s)
        v = valuation(Delta, ell)
        A2_dec = []
        for i_s, w in prec["factors"].items():
            A2_dec += [tuple(x) for x in w["residue_decomposition"]]
        for i, fi in enumerate(R["factors"]):
            if str(i) not in prec["factors"]:
                A2_dec += [(1, len(g) - 1) for g, e in factor_mod(fi, ell)]
        ref = reference_at_prime(minpolys, ell, order) if minpolys else None
        restricted = False
        if ref is None:
            if v <= 2:
                ref = restricted_reference(A2_dec, ell, order); restricted = True
            else:
                rec["primes"][ell_s] = {"v_disc_f": v, "reference": "unavailable (explicit N over budget, v > 2)", "compared": False}
                continue
        entry = {"v_disc_f": v, "reference": ref, "restricted": restricted, "compared": True}
        lr = L["ramified"].get(ell_s)
        if lr is None or lr["status"] != "ok":
            entry["pipeline"] = lr["status"] if lr else "absent"
            entry["ok"] = None if (ref is None or ref.get("e", 1) % ell == 0) else False
            entry["note"] = "pipeline has no local data here (wild)" if lr and lr["status"].startswith("wild") else "pipeline failed"
            rec["primes"][ell_s] = entry
            continue
        pe, pf = lr["e"], lr["f"]
        pg = order // (pe * pf)
        ok = (pe, pf, pg) == (ref["e"], ref["f"], ref["g"])
        entry["pipeline"] = {"e": pe, "f": pf, "g": pg}
        # conductor aggregate vs v_ell(d_N) read off N (tame: g f (e-1))
        if ell_s in CJ["primes"]:
            s = sum(T["degrees"][c["chi"] - 1] * c["f_ell"] for c in CJ["primes"][ell_s]["conductor_exponents"])
            entry["sum_chi1_f_ell"] = s
            entry["v_disc_N_reference"] = ref["v_disc_N"]
            ok = ok and (ref["v_disc_N"] is None or s == ref["v_disc_N"])
        entry["ok"] = ok
        all_ok = all_ok and ok
        rec["primes"][ell_s] = entry
    rec["all_compared_ok"] = all_ok
    rec["seconds"] = round(time.time() - t0, 1)
    return rec