"""The decision rule for the functional equation, and the zeta anchor.

Runs the functional-equation test at a fixed pair of arguments against an
explicit tail bound, and applies the same rule to deliberately perturbed data
(a wrong root number, a wrong conductor, a wrong Euler factor, a wrong
Frobenius class) so that the test's power is measured rather than assumed.
Also computes the residue of the Dedekind zeta function of the subfield
generated by a root, from f alone, and compares it with the product of the
L-values obtained from the character data.
"""
from __future__ import annotations
import math, cmath
import mpmath

from .analytic import Kernel, dirichlet_coefficients, theta, zeta_subfield_coefficients
from .chartable import is_prime
from .ramified import factor_mod, decide_prime_for_factor, discriminant, factor_over_Z
from .archimedean import real_root_count
from .filtration import HardFailure

# ------------------------------------------------------------------ 

def M_star(a, b):
    d = a + b
    return 2 ** (d / 2) / math.pi ** (1 + b) * (4 / (math.pi * d) + math.pi ** (b / 2) * math.gamma(b / 2 + 1) * (4 / (math.pi * d)) ** (b / 2 + 1))

def K_chi(a, b):
    return 2 ** ((b + a + b) / 2) * M_star(a, b)

def E_chi(d, a, b, f, t, X):
    """E_chi(t, X) of  (exact incomplete Gamma); requires alpha X^{2/d} >= max(d(d-3)/4, 2 kappa, 1)."""
    alpha = math.pi * d / 2 * (t / math.sqrt(f)) ** (2 / d)
    kappa = d * (d - 1) / 4
    y = alpha * X ** (2 / d)
    if y < max(d * (d - 3) / 4, 2 * kappa, 1):
        return None
    K = K_chi(a, b)
    if kappa == 0:
        G = float(mpmath.e1(y))
    else:
        G = float(mpmath.gammainc(kappa, y, mpmath.inf))
    return 2 ** (d - 1) * K * math.sqrt(f) / t * d / 2 * alpha ** (-kappa) * G

def E_total(d, a, b, f, t, X):
    e1, e2 = E_chi(d, a, b, f, t, X), E_chi(d, a, b, f, 1 / t, X)
    if e1 is None or e2 is None:
        return None
    return e1 + e2

# ------------------------------------------------------------------ the decision rule and the falsifier

T_FIXED = (1.25, 1.6)      # bounded away from 1 and from each other

def discrepancy(S, Sbar, W, t):
    """Delta_chi(t, X; W) = S_chi(t) - W t^{-1} S_{conj chi}(1/t) ('s normalization)."""
    return S(t) - W * Sbar(1 / t) / t

EVAL_REL = 1e-13   # double-precision evaluation allowance (the "certified evaluation error" of the rule)

def eval_error(S_t, Sb_t, X):
    return EVAL_REL * (1 + abs(S_t) + abs(Sb_t)) * math.log(X + 2)

_THETA_CACHE = {}

def _theta_cached(coeffs, g, sf, t, X):
    key = (id(coeffs), id(g), sf, t, X)
    if key not in _THETA_CACHE:
        _THETA_CACHE[key] = theta(coeffs, g, sf, t, X)
    return _THETA_CACHE[key]

def decide(coeffs, coeffs_bar, g, d, a, b, f, W, X, ts=T_FIXED):
    """Returns the list of (t, |Delta|, E, rejected)."""
    sf = math.sqrt(f)
    S = lambda t: _theta_cached(coeffs, g, sf, t, X)
    Sb = lambda t: _theta_cached(coeffs_bar, g, sf, t, X)
    out = []
    for t in ts:
        E = E_total(d, a, b, f, t, X)
        D = abs(discrepancy(S, Sb, W, t))
        ev = eval_error(S(t), Sb(1 / t) / t, X)
        out.append({"t": t, "Delta": D, "E": E, "eval_error": ev, "rejected": (E is not None and D > E + ev), "resolved": E is not None})
    return out

def falsify(coeffs, coeffs_bar, euler, euler_bar, g, d, a, b, f, W, X, ell_ram, ell_unram_small, log=print):
    """Run the decision rule on the true data and on deliberately perturbed data:
    wrong W, conductor off by ell^{+-1} (4.2), Euler factor removed at a ramified
    prime (4.3), Frobenius data changed at a small unramified prime (last paragraph).
    True data must pass; each perturbation must be rejected whenever its a priori condition
    (decided from the computed sums) holds, else it is recorded as unresolved at this X."""
    rep = {}
    base = decide(coeffs, coeffs_bar, g, d, a, b, f, W, X)
    rep["true"] = base
    if any(r["rejected"] for r in base):
        raise HardFailure("the decision rule rejects the true data")
    sf = math.sqrt(f)
    Sb = lambda t: theta(coeffs_bar, g, sf, t, X)
    # (i) wrong root number: W' = -W (and W' = i W, -i W when W is not real)
    cands = [-W] + ([1j * W, -1j * W] if abs(W.imag) > 1e-12 or True else [])
    rep["wrong_W"] = []
    for Wp in cands:
        r = decide(coeffs, coeffs_bar, g, d, a, b, f, Wp, X)
        # a priori condition of  at each t
        must = []
        for entry in r:
            t = entry["t"]
            Eb = E_chi(d, a, b, f, 1 / t, X)
            cond = entry["E"] is not None and Eb is not None and abs(W - Wp) * abs(Sb(1 / t)) > entry["E"] + abs(W - Wp) * Eb
            must.append(cond)
            if cond and not entry["rejected"]:
                raise HardFailure(f"falsifier: W' = {Wp} not rejected although 's condition holds at t = {t}")
        rep["wrong_W"].append({"W'": [Wp.real, Wp.imag], "tests": r, "condition_holds": must,
                               "verdict": "rejected" if any(e["rejected"] for e in r) else "unresolved"})
    # (ii) conductor wrong at one ramified prime
    rep["wrong_conductor"] = []
    for ell in ell_ram:
        for k in (1, -1):
            fp = f * ell ** k
            if fp < 1:
                continue
            r = decide(coeffs, coeffs_bar, g, d, a, b, fp, W, X)
            rep["wrong_conductor"].append({"ell": ell, "k": k, "tests": r,
                                           "verdict": "rejected" if any(e["rejected"] for e in r) else "unresolved"})
    # (iii) Euler factor wrong at a ramified prime: replace P_ell by 1 (and by its reciprocal-type variant 1 - T)
    rep["wrong_euler_ramified"] = []
    for ell in ell_ram:
        if ell not in euler:
            rep["wrong_euler_ramified"].append({"ell": ell, "verdict": "beyond X (undetectable at this truncation)"})
            continue
        for label, Pp in (("P=1", [1 + 0j]), ("P=1-T", [1 + 0j, -1 + 0j])):
            e2 = dict(euler); e2[ell] = Pp
            e2b = dict(euler_bar); e2b[ell] = [c.conjugate() for c in Pp]
            if e2[ell] == euler[ell] or (len(euler[ell]) == len(Pp) and all(abs(x - y) < 1e-12 for x, y in zip(euler[ell], Pp))):
                continue
            c2, c2b = dirichlet_coefficients(e2, X), dirichlet_coefficients(e2b, X)
            r = decide(c2, c2b, g, d, a, b, f, W, X)
            rep["wrong_euler_ramified"].append({"ell": ell, "perturbation": label, "tests": r,
                                                "verdict": "rejected" if any(e["rejected"] for e in r) else "unresolved"})
    # (iv) wrong Frobenius data at a small unramified prime: P_ell replaced by (1 - T)^d (identity class)
    rep["wrong_frobenius"] = []
    for ell in ell_unram_small:
        Pp = [1 + 0j]
        for _ in range(d):
            Pp = [x - (Pp[i - 1] if i else 0) for i, x in enumerate(Pp + [0j])]
        if all(abs(x - y) < 1e-12 for x, y in zip(euler[ell], Pp)) and len(euler[ell]) == len(Pp):
            continue
        e2 = dict(euler); e2[ell] = Pp
        e2b = dict(euler_bar); e2b[ell] = Pp
        c2, c2b = dirichlet_coefficients(e2, X), dirichlet_coefficients(e2b, X)
        r = decide(c2, c2b, g, d, a, b, f, W, X)
        rep["wrong_frobenius"].append({"ell": ell, "tests": r,
                                       "verdict": "rejected" if any(e["rejected"] for e in r) else "unresolved"})
    return rep

# ------------------------------------------------------------------ the trivial character

def trivial_character_test(X, ts=T_FIXED):
    g = lambda x: 2 * math.exp(-math.pi * x * x)
    out = []
    for t in ts:
        S = sum(g(m * t) for m in range(1, X + 1))
        S2 = sum(g(m / t) for m in range(1, X + 1))
        R = S - (S2 / t + 1 / t - 1)
        E = E_total(1, 1, 0, 1, t, X)
        ev = eval_error(S, S2 / t, X)
        out.append({"t": t, "S": S, "residual": abs(R), "E": E, "eval_error": ev, "ok": E is not None and abs(R) <= E + ev})
        if not out[-1]["ok"]:
            raise HardFailure(f"trivial character identity fails at t = {t}: residual {abs(R)}, E = {E}")
    return out

# ------------------------------------------------------------------ the zeta anchor

def dedekind_data(f, X):
    """From f alone: residue degrees at every prime <= X, |d_K|, r_1, r_2 for K = Q[x]/(f)."""
    n = len(f) - 1
    D = abs(discriminant(f))
    rd, dK = {}, 1
    for q in range(2, X + 1):
        if not is_prime(q):
            continue
        if D % q:
            rd[q] = [len(g) - 1 for g, e in factor_mod(f, q)]
        else:
            w = decide_prime_for_factor(f, q)
            rd[q] = [fd for e_, fd in w["residue_decomposition"]]
            dK *= q ** w["v_disc_O"]
    # primes > X dividing D still contribute to |d_K|
    Dq = D
    for q in list(rd):
        while Dq % q == 0:
            Dq //= q
    if Dq > 1:
        from .ramified import factorint
        for q in factorint(Dq):
            w = decide_prime_for_factor(f, q)
            dK *= q ** w["v_disc_O"]
    r1 = real_root_count(f)
    return rd, dK, r1, (n - r1) // 2

def zeta_anchor(f, X, table_side, log=print, ts=(1.15, 1.35, 1.6), cap=20000):
    """table_side(): callable returning prod_{chi != 1} L(1, chi)^{n_chi(H)} for the character side;
    None if unavailable.  The Dedekind side uses its own X (tail bound < 1e-13 for the
    kernel of Gamma_R^{r1} Gamma_C^{r2} at sqrt|d_K|, capped), since |d_K| is usually much
    larger than the conductors of the characters.  Returns the anchor record."""
    rd0, dK, r1, r2 = dedekind_data(f, 2)
    a_, b_ = r1 + r2, r2
    g = Kernel(a_, b_)
    sd = math.sqrt(dK)
    from .analytic import tail_estimate
    XA = 50
    while XA < cap and tail_estimate(a_ + b_, g, sd, 1 / max(ts), XA, factor=3) >= 1e-13:
        XA = int(XA * 1.25) + 1
    X = max(X, XA)
    rd, dK, r1, r2 = dedekind_data(f, X)
    b = zeta_subfield_coefficients(rd, X)
    Th = lambda t: sum(b[m] * g(m * t / sd) for m in range(1, X + 1))
    # Theta(t) = t^{-1} Theta(1/t) + R1 (t^{-1} - 1): fit R1 at ts[0], check at the others
    R1 = (Th(ts[0]) - Th(1 / ts[0]) / ts[0]) / (1 / ts[0] - 1)
    checks = []
    for t in ts[1:]:
        lhs = Th(t); rhs = Th(1 / t) / t + R1 * (1 / t - 1)
        d = a_ + b_
        E = E_total(d, a_, b_, dK, t, X)
        checks.append({"t": t, "defect": abs(lhs - rhs), "E": E, "ok": E is None or abs(lhs - rhs) <= E + eval_error(lhs, rhs, X)})
    rho = float(R1 / (sd * math.pi ** (-r2)))     # residue of zeta_K at s = 1
    rec = {"field": "Q(alpha), f = " + str(f), "|d_K|": dK, "r1": r1, "r2": r2, "X": X,
           "Lambda_residue_R1": R1, "zeta_residue_rho_K": rho, "theta_checks": checks}
    if any(not c["ok"] for c in checks):
        raise HardFailure(f"zeta anchor: theta identity of zeta_K fails: {checks}")
    cs = table_side()
    if cs is not None:
        rec["character_side_product_L1"] = float(cs)
        rec["relative_difference"] = float(abs(cs - rho) / abs(rho))
        rec["anchor_ok"] = bool(rec["relative_difference"] < 1e-8)
        if not rec["anchor_ok"]:
            raise HardFailure(f"zeta anchor fails: rho_K = {rho} vs prod L(1,chi)^n = {cs}")
    return rec

def lambda_at_one(coeffs, coeffs_bar, g, f, W, X):
    """Lambda(1, chi) = int_1^inf Theta_chi(t) dt + W int_1^inf Theta_{conj chi}(t) t^{-1} dt (s = 1)."""
    sf = math.sqrt(f)
    Th = lambda t: theta(coeffs, g, sf, t, X)
    Thb = lambda t: theta(coeffs_bar, g, sf, t, X)
    T = 1.0
    # integrate on [1, T_max] with Gauss-Legendre in log scale
    import numpy as np
    Tmax = 1.0
    while abs(Th(Tmax)) + abs(Thb(Tmax)) > 1e-18 and Tmax < 1e4:
        Tmax *= 1.5
    xs, ws = np.polynomial.legendre.leggauss(64)
    # composite rule: 6 panels in log t on [0, log Tmax]
    I1 = I2 = 0.0
    edges = [math.log(Tmax) * k / 6 for k in range(7)]
    for lo, hi in zip(edges, edges[1:]):
        u = (xs + 1) / 2 * (hi - lo) + lo
        w = ws * (hi - lo) / 2
        I1 += sum(wi * Th(math.exp(ui)) * math.exp(ui) for ui, wi in zip(u, w))
        I2 += sum(wi * Thb(math.exp(ui)) for ui, wi in zip(u, w))
    return complex(I1 + W * I2)