"""Matching the local roots to the global numbering.

The permutations that identify the local roots with the global ones form a
coset of the Galois group; one is found by a structural filter followed by an
invariant congruence.  A second, independently chosen matching is computed and
the two transported local data are checked to be conjugate in G, so that the
recorded decomposition and inertia groups are well defined.
"""
from __future__ import annotations
import random

from .perm import PermGroup, mul, inverse, identity, symmetric, cycle_type
from .padic import PrecisionExhausted
from .local import LocalGalois, _orbits

def matchings(local: LocalGalois, G: PermGroup, chain, k_policy, transversal):
    """Survivors rho of the chain test (single level: F(beta^rho) = c mod ell^k) among the
    given transversal of S_n/G, after the structural filter rho^{-1} D rho <= G.
    Convention: the test F(beta^rho) = F(alpha) identifies alpha_i = beta_{rho(i)} (rho = tau^{-1} in the
    convention of the derivation), so D in the global numbering is rho^{-1} D_beta rho and a global root
    set S corresponds to the local set rho(S)."""
    F, c = chain
    K = local.K
    target = K.from_int(c)
    prec = min(K.prec - K.E, local.E * k_policy)
    surv = []
    for idx, rho in enumerate(transversal):
        # structural filter: rho^{-1} phi rho and rho^{-1} tau rho in G
        ok = True
        for g in (local.phi, local.tau):
            if not G.contains(mul(inverse(rho), mul(g, rho))):
                ok = False
                break
        if not ok:
            continue
        v = local.evaluate(F, rho)
        if K.eq(v, target, prec):
            surv.append(idx)
    return surv

def transport(local: LocalGalois, rho):
    """(D, I, Frobenius representative) in the global numbering for the matching rho."""
    conj = lambda g: mul(inverse(rho), mul(g, rho))
    n = len(rho)
    D = PermGroup([conj(local.phi), conj(local.tau)], n=n)
    I = PermGroup([conj(local.tau)], n=n)
    return D, I, conj(local.phi)

def simultaneously_conjugate(G: PermGroup, data1, data2):
    """An element g of G with g D1 g^-1 = D2, g I1 g^-1 = I2 and g Fr1 I1 g^-1 = Fr2 I2."""
    D1, I1, Fr1 = data1
    D2, I2, Fr2 = data2
    S1, S2 = set(D1.elements()), set(D2.elements())
    J1, J2 = set(I1.elements()), set(I2.elements())
    for g in G.elements():
        gi = inverse(g)
        if {mul(g, mul(x, gi)) for x in S1} != S2:
            continue
        if {mul(g, mul(x, gi)) for x in J1} != J2:
            continue
        fr = mul(g, mul(Fr1, gi))
        if not any(mul(fr, i) == Fr2 or mul(Fr2, i) == fr for i in J2) and not (mul(inverse(Fr2), fr) in J2):
            continue
        return g
    return None

def local_data_at(f, ell, G, cl, chain, policy, ram_data, v_disc, seed=0, log=print):
    """Build the local field at ell, match it to the global numbering and check that a second,
    independent matching gives conjugate data.  ram_data: the ramification indices and residue
    degrees of ell in the fields generated by the irreducible factors of f.
    Returns the record."""
    n = G.n
    k_policy = policy.k(ell, v_disc=v_disc)
    # roots are accurate to (ring precision) - v(f'(beta)); v(f'(beta)) <= v_ell(disc f), so the
    # local field carries v_disc + 1 extra digits for the comparison at the policy precision
    k = k_policy + (v_disc or 0) + 1
    while True:
        try:
            local = LocalGalois(f, ell, k, ram_data, seed=seed, log=log)
            break
        except (PrecisionExhausted, AssertionError, RuntimeError) as e:
            k *= 2
            policy.extra.setdefault(str(ell), []).append({"label": "local root finding", "k": k})
            if k > 4096:
                raise
    Sn = symmetric(n)
    from .resolvent import coset_transversal
    T = coset_transversal(Sn, G)
    surv = matchings(local, G, chain, k_policy, T)
    if len(surv) != 1:
        raise RuntimeError(f"matching at {ell}: {len(surv)} survivors in the transversal (expected 1)")
    rho1 = T[surv[0]]
    # an independent second matching: a second, randomly chosen transversal
    rng = random.Random(seed + 1)
    T2 = [mul(t, rng.choice(G.elements())) for t in T]
    surv2 = matchings(local, G, chain, k_policy, T2)
    if len(surv2) != 1:
        raise RuntimeError(f"second matching at {ell}: {len(surv2)} survivors")
    rho2 = T2[surv2[0]]
    d1, d2 = transport(local, rho1), transport(local, rho2)
    g = simultaneously_conjugate(G, d1, d2)
    if g is None:
        raise RuntimeError(f"well-definedness failure at {ell}: the two matchings give non-conjugate local data")
    assert G.contains(mul(inverse(rho1), rho2)), "the two matchings do not differ by an element of G"
    D, I, Fr = d1
    rec = {"ell": ell, "k": local.k, "field": {"E": local.E, "F": local.F},
           "e": local.e, "f": local.f, "|D|": D.order(),
           "D_generators": [[i + 1 for i in g_] for g_ in D.generators],
           "I_generators": [[i + 1 for i in g_] for g_ in I.generators],
           "frobenius_rep": [i + 1 for i in Fr],
           "frobenius_coset_class": sorted({cl.class_of(mul(Fr, i)) + 1 for i in I.elements()}),
           "matching": [i + 1 for i in rho1], "matching2": [i + 1 for i in rho2],
           "conjugator": [i + 1 for i in g],
           "inertia_orbit_sizes": sorted(len(o) for o in _orbits(I, n)),
           "decomposition_orbit_sizes": sorted(len(o) for o in _orbits(D, n)),
           "ramification_indices_from_factors": sorted(e for e, fdeg in ram_data),
           "factor_degrees_from_factors": sorted(e * fdeg for e, fdeg in ram_data)}
    # inertia and decomposition orbit sizes against the factor data
    rec["inertia_orbits_match_factors"] = _multiset_match(rec["inertia_orbit_sizes"], ram_data, n, inertia=True)
    rec["decomposition_orbits_match_factors"] = rec["decomposition_orbit_sizes"] == rec["factor_degrees_from_factors"]
    return rec, local, D, I, Fr

def _multiset_match(sizes, ram_data, n, inertia=True):
    """Inertia orbits: each factor (e_j, f_j) contributes f_j orbits of size e_j."""
    want = sorted(e for e, fdeg in ram_data for _ in range(fdeg))
    return sizes == want