"""The primes ramified in the Galois closure.

A prime ramifies exactly when it divides the discriminant of the ring of
integers of one of the fields generated by an irreducible factor of f.  Each
prime is decided by one of three routes, and the decision is recorded with a
witness a verifier can recheck: an odd discriminant valuation; the Dedekind
criterion; or the Pohst-Zassenhaus round-2 construction of the maximal order
at the prime, which also yields the decomposition of the prime into
ramification indices and residue degrees.
"""
from __future__ import annotations
from fractions import Fraction
import math
import random

import sympy
from sympy import Poly, symbols, factorint, ZZ, GF

from .fpoly import (nullspace, rref, rank, poly_mul, poly_mod, poly_divmod, poly_gcd,
                    poly_monic, poly_sub, poly_add, poly_trim, roots_mod_p, mat_vec)

X = symbols("x")

# ------------------------------------------------------------ polynomials over Z

def poly_from_coeffs(coeffs):
    """coeffs ascending -> sympy Poly."""
    return Poly(list(reversed(coeffs)), X, domain=ZZ)

def coeffs_of(P):
    return [int(c) for c in reversed(P.all_coeffs())]

def discriminant(coeffs):
    return int(poly_from_coeffs(coeffs).discriminant())

def factor_over_Z(coeffs):
    P = poly_from_coeffs(coeffs)
    _, facs = P.factor_list()
    out = []
    for q, mult in facs:
        if mult > 1:
            raise ValueError("f is not separable")
        out.append(coeffs_of(q))
    return out

def factor_mod(coeffs, ell):
    """Factorization of f mod ell: list of (monic irreducible coeffs ascending, exponent)."""
    P = Poly(list(reversed(coeffs)), X, modulus=ell)
    _, facs = P.factor_list()
    out = []
    for q, mult in facs:
        c = [int(a) % ell for a in reversed(q.all_coeffs())]
        out.append((c, mult))
    return out

def valuation(n, ell):
    v = 0
    while n % ell == 0:
        n //= ell
        v += 1
    return v

# ------------------------------------------------------------ field arithmetic

class NumberFieldPower:
    """K = Q[x]/(f), elements as Fraction vectors in the power basis."""
    def __init__(self, f):
        self.f = [Fraction(c) for c in f]
        self.n = len(f) - 1
        assert self.f[-1] == 1

    def mul(self, a, b):
        n = self.n
        prod = [Fraction(0)] * (2 * n - 1)
        for i, x in enumerate(a):
            if x:
                for j, y in enumerate(b):
                    if y:
                        prod[i + j] += x * y
        # reduce mod f (monic)
        for i in range(2 * n - 2, n - 1, -1):
            c = prod[i]
            if c:
                for j in range(n + 1):
                    prod[i - n + j] -= c * self.f[j]
        return prod[:n]

def det_fraction(M):
    n = len(M)
    A = [row[:] for row in M]
    det = Fraction(1)
    for c in range(n):
        piv = next((r for r in range(c, n) if A[r][c] != 0), None)
        if piv is None:
            return Fraction(0)
        if piv != c:
            A[c], A[piv] = A[piv], A[c]
            det = -det
        det *= A[c][c]
        inv = 1 / A[c][c]
        for r in range(c + 1, n):
            if A[r][c] != 0:
                f = A[r][c] * inv
                A[r] = [x - f * y for x, y in zip(A[r], A[c])]
    return det

def inverse_fraction(M):
    n = len(M)
    A = [row[:] + [Fraction(1 if i == j else 0) for j in range(n)] for i, row in enumerate(M)]
    for c in range(n):
        piv = next((r for r in range(c, n) if A[r][c] != 0), None)
        if piv is None:
            raise ZeroDivisionError("singular")
        A[c], A[piv] = A[piv], A[c]
        inv = 1 / A[c][c]
        A[c] = [x * inv for x in A[c]]
        for r in range(n):
            if r != c and A[r][c] != 0:
                f = A[r][c]
                A[r] = [x - f * y for x, y in zip(A[r], A[c])]
    return [row[n:] for row in A]

def vec_mat(v, M):
    n = len(M[0])
    return [sum(v[i] * M[i][j] for i in range(len(v))) for j in range(n)]

def hnf_rows(rows, n):
    """Z-basis (n rows) of the lattice spanned by integer rows of length n (full rank assumed)."""
    A = [list(r) for r in rows]
    basis = []
    for c in range(n):
        # gather rows with nonzero at column c, gcd them
        while True:
            nz = [r for r in A if r[c] != 0]
            if len(nz) <= 1:
                break
            nz.sort(key=lambda r: abs(r[c]))
            pivot = nz[0]
            for r in nz[1:]:
                q = r[c] // pivot[c]
                for j in range(n):
                    r[j] -= q * pivot[j]
        nz = [r for r in A if r[c] != 0]
        if nz:
            piv = nz[0]
            if piv[c] < 0:
                piv = [-x for x in piv]
            basis.append(piv)
            A = [r for r in A if r is not nz[0]]
            A = [r for r in A if any(r)]
        else:
            raise ValueError("lattice not of full rank")
    return basis

# ------------------------------------------------------------ Round 2 at ell

class OrderAtPrime:
    """An order Z[alpha] <= O <= ell^{-t} Z[alpha], basis rows in the power basis."""
    def __init__(self, K: NumberFieldPower, ell, basis=None):
        self.K = K
        self.ell = ell
        n = K.n
        self.B = basis if basis is not None else [[Fraction(1 if i == j else 0) for j in range(n)] for i in range(n)]
        self.Binv = inverse_fraction(self.B)
        self.n = n
        self._struct = None

    def index_valuation(self):
        """t with [O: Z[alpha]] = ell^t."""
        d = det_fraction(self.B)
        return valuation(d.denominator, self.ell) - valuation(d.numerator, self.ell)

    def structure_constants(self):
        """s[a][b] = integer coordinates of b_a b_b in the basis."""
        if self._struct is None:
            n = self.n
            s = [[None] * n for _ in range(n)]
            for a in range(n):
                for b in range(a, n):
                    prod = self.K.mul(self.B[a], self.B[b])
                    co = vec_mat(prod, self.Binv)
                    assert all(c.denominator == 1 for c in co), "not closed under multiplication"
                    s[a][b] = s[b][a] = [int(c) for c in co]
            self._struct = s
        return self._struct

    def algebra_mod_ell(self):
        s = self.structure_constants()
        ell = self.ell
        return FiniteAlgebra(self.n, [[[c % ell for c in s[a][b]] for b in range(self.n)] for a in range(self.n)], ell)

    def radical_lattice(self):
        """Basis (rows, coordinates in the basis of O) of I_ell = preimage of nil(O/ell)."""
        A = self.algebra_mod_ell()
        N = A.nilradical()
        rows = [[self.ell if i == j else 0 for j in range(self.n)] for i in range(self.n)] + [list(v) for v in N]
        return hnf_rows(rows, self.n), len(N)

    def multiplier_ring(self):
        """O' = [I: I]; returns new OrderAtPrime and whether it equals O."""
        n, ell = self.n, self.ell
        C, nildim = self.radical_lattice()
        Cq = [[Fraction(x) for x in row] for row in C]
        Cinv = inverse_fraction(Cq)
        s = self.structure_constants()
        # matrix of the map O -> End(I/ell I): column a = mult by b_a, rows (j,m)
        cols = []
        for a in range(n):
            col = []
            for j in range(n):
                # b_a * c_j in O-coords
                vec = [0] * n
                for m, cm in enumerate(C[j]):
                    if cm:
                        for t in range(n):
                            vec[t] += cm * s[a][m][t]
                # in I-basis
                y = vec_mat([Fraction(x) for x in vec], Cinv)
                assert all(v.denominator == 1 for v in y), "I is not an ideal?"
                col.extend(int(v) % ell for v in y)
            cols.append(col)
        M = [[cols[a][i] for a in range(n)] for i in range(n * n)]
        ker = nullspace(M, ell, ncols=n)
        rows = [[ell if i == j else 0 for j in range(n)] for i in range(n)] + [list(v) for v in ker]
        U = hnf_rows(rows, n)  # basis of U in O-coords
        newB = [[Fraction(x, ell) for x in vec_mat([Fraction(u) for u in row], self.B)] for row in U]
        Onew = OrderAtPrime(self.K, ell, newB)
        same = Onew.index_valuation() == self.index_valuation()
        return Onew, same, nildim

    def is_ell_maximal_and_unramified(self):
        C, nildim = self.radical_lattice()
        return nildim == 0


class FiniteAlgebra:
    """Commutative F_ell-algebra with structure constants s[a][b] (vectors)."""
    def __init__(self, m, s, ell):
        self.m, self.s, self.ell = m, s, ell

    def mul(self, x, y):
        m, ell = self.m, self.ell
        out = [0] * m
        for a in range(m):
            if x[a]:
                for b in range(m):
                    if y[b]:
                        f = x[a] * y[b]
                        sab = self.s[a][b]
                        for t in range(m):
                            if sab[t]:
                                out[t] = (out[t] + f * sab[t]) % ell
        return out

    def one(self):
        # find identity: solve for vector u with u*b_a = b_a for all a -- linear system
        m, ell = self.m, self.ell
        rows, rhs = [], []
        for a in range(m):
            for t in range(m):
                rows.append([self.s[u][a][t] % ell for u in range(m)])
                rhs.append(1 if a == t else 0)
        aug = [r + [b] for r, b in zip(rows, rhs)]
        R, piv = rref(aug, ell)
        sol = [0] * m
        for i, c in enumerate(piv):
            if c == m:
                raise ValueError("no identity")
            sol[c] = R[i][m]
        return sol

    def power(self, x, k):
        r = self.one()
        while k:
            if k & 1:
                r = self.mul(r, x)
            x = self.mul(x, x)
            k >>= 1
        return r

    def frobenius_matrix(self):
        """Matrix F with F[t][a] = coordinate t of b_a^ell."""
        m = self.m
        cols = []
        for a in range(m):
            e = [1 if i == a else 0 for i in range(m)]
            cols.append(self.power(e, self.ell))
        return [[cols[a][t] for a in range(m)] for t in range(m)]

    def nilradical(self):
        m, ell = self.m, self.ell
        F = self.frobenius_matrix()
        r = 0
        while ell ** r < m:
            r += 1
        r = max(r, 1)
        Fr = F
        for _ in range(r - 1):
            Fr = [[sum(Fr[i][k] * F[k][j] for k in range(m)) % ell for j in range(m)] for i in range(m)]
        return nullspace(Fr, ell, ncols=m)

    def minimal_polynomial(self, x):
        """Monic minimal polynomial of x (ascending coefficients) over F_ell."""
        m, ell = self.m, self.ell
        powers = [self.one()]
        while True:
            # test dependency
            M = [[powers[k][t] for k in range(len(powers))] for t in range(m)]
            ker = nullspace(M, ell, ncols=len(powers))
            if ker:
                v = ker[0]
                inv = pow(v[-1], -1, ell)
                return [(c * inv) % ell for c in v]
            powers.append(self.mul(powers[-1], x))

    def residue_decomposition(self, rng=random):
        """List of (e_j, f_j) for the local components of the algebra."""
        m, ell = self.m, self.ell
        N = self.nilradical()
        nd = len(N)
        # projection with kernel N: rows spanning a complement of N
        Nrref, piv = rref(N, ell) if N else ([], [])
        proj_rows = [[1 if i == j else 0 for j in range(m)] for i in range(m) if i not in piv]
        # coordinates mod N: reduce vector by N (rref) then take non-pivot coordinates
        def mod_N(v):
            v = list(v)
            for row, c in zip(Nrref, piv):
                if v[c]:
                    f = v[c]
                    v = [(x - f * y) % ell for x, y in zip(v, row)]
            return [v[i] for i in range(m) if i not in piv]
        F = self.frobenius_matrix()
        FmI = [[(F[i][j] - (1 if i == j else 0)) % ell for j in range(m)] for i in range(m)]
        cols = [mod_N([FmI[i][a] for i in range(m)]) for a in range(m)]
        Mz = [[cols[a][i] for a in range(m)] for i in range(len(cols[0]))] if cols and cols[0] else []
        Z = nullspace(Mz, ell, ncols=m) if Mz else [[1 if i == j else 0 for j in range(m)] for i in range(m)]
        nprimes = len(Z) - nd
        if nprimes == 1:
            f = m - nd
            assert m % f == 0
            return [(m // f, f)]
        # find y in Z not in N + F_ell 1
        one = self.one()
        span = [list(v) for v in N] + [one]
        for y in Z:
            if rank(span + [y], ell) > rank(span, ell):
                break
        else:
            raise RuntimeError("no splitting element")
        mp = self.minimal_polynomial(y)
        roots = roots_mod_p(mp, ell, rng)
        assert len(roots) >= 2
        # factor mp = prod (x - a)^k
        facs = []
        rem = mp
        for a in roots:
            k = 0
            while True:
                q, r = poly_divmod(rem, [(-a) % ell, 1], ell)
                if r:
                    break
                rem, k = q, k + 1
            facs.append(([(-a) % ell, 1], k))
        assert len(rem) == 1
        out = []
        for i, (lin, k) in enumerate(facs):
            qi = [1]
            for _ in range(k):
                qi = poly_mul(qi, lin, ell)
            cof = [1]
            for j, (lin2, k2) in enumerate(facs):
                if j != i:
                    for _ in range(k2):
                        cof = poly_mul(cof, lin2, ell)
            inv = poly_inverse_mod(cof, qi, ell)
            h = poly_mod(poly_mul(cof, inv, ell), mp, ell)
            e_i = self.eval_poly(h, y)
            # component A e_i
            vecs = [self.mul(e_i, [1 if t == a else 0 for t in range(m)]) for a in range(m)]
            R, pv = rref(vecs, ell)
            sub = R  # basis of the component (rows)
            d = len(sub)
            # structure constants of the component: products of basis vectors expressed in sub-basis
            s = [[None] * d for _ in range(d)]
            for a in range(d):
                for b in range(d):
                    prod = self.mul(sub[a], sub[b])
                    s[a][b] = [prod[c] for c in pv]  # coordinates read at pivots (rref basis)
            comp = FiniteAlgebra(d, s, ell)
            out.extend(comp.residue_decomposition(rng))
        return out

    def eval_poly(self, h, y):
        r = [0] * self.m
        for c in reversed(h):
            r = self.mul(r, y)
            r[0] = r[0]  # placeholder
            one = self.one()
            r = [(a + c * b) % self.ell for a, b in zip(r, one)]
        return r


def poly_inverse_mod(a, mod, p):
    """Inverse of a modulo mod over F_p (extended Euclid)."""
    r0, r1 = poly_trim(list(mod)), poly_mod(a, mod, p)
    s0, s1 = [], [1]
    while r1:
        q, r = poly_divmod(r0, r1, p)
        r0, r1 = r1, r
        s0, s1 = s1, poly_sub(s0, poly_mul(q, s1, p), p)
    # r0 = gcd (constant)
    assert len(r0) == 1, "not invertible"
    inv = pow(r0[0], -1, p)
    return poly_mod([(c * inv) % p for c in s0], mod, p)

# ------------------------------------------------------------ the decision

def dedekind_criterion(fi, ell):
    """Returns (is_ell_maximal, factorization mod ell, gcd data)."""
    facs = factor_mod(fi, ell)
    # lift, h = (f - prod g_j^{e_j})/ell
    P = poly_from_coeffs(fi)
    prod = Poly(1, X, domain=ZZ)
    for g, e in facs:
        glift = Poly(list(reversed([c if c <= ell // 2 else c - ell for c in g])), X, domain=ZZ)
        prod *= glift ** e
    diff = (P - prod)
    hc = coeffs_of(diff)
    assert all(c % ell == 0 for c in hc)
    hbar = [(c // ell) % ell for c in hc]
    maximal = True
    gcds = []
    for g, e in facs:
        if e >= 2:
            gg = poly_gcd(hbar, g, ell) if poly_trim(list(hbar)) else g
            gcds.append((g, len(gg) - 1))
            if len(gg) - 1 > 0:
                maximal = False
    return maximal, facs, gcds


def decide_prime_for_factor(fi, ell):
    """Decide one irreducible factor and one prime. Returns witness dict."""
    v = valuation(discriminant(fi), ell)
    out = {"v_disc_f": v}
    if v % 2 == 1:
        out.update({"method": "odd valuation", "ramified": True})
    maximal, facs, gcds = dedekind_criterion(fi, ell)
    out["factorization_mod_ell"] = [{"factor": g, "exponent": e} for g, e in facs]
    if maximal:
        ram = any(e >= 2 for _, e in facs)
        out.update({"method": out.get("method", "Dedekind criterion"), "Z[alpha]_ell_maximal": True,
                    "dedekind_gcd_degrees": [(g, d) for g, d in gcds],
                    "ramified": ram, "v_disc_O": v,
                    "residue_decomposition": sorted([(e, len(g) - 1) for g, e in facs]),
                    "index_valuation": 0})
        return out
    # Round 2
    K = NumberFieldPower(fi)
    O = OrderAtPrime(K, ell)
    iterations = 0
    while True:
        Onew, same, nildim = O.multiplier_ring()
        iterations += 1
        if same:
            break
        O = Onew
    t = O.index_valuation()
    C, nildim = O.radical_lattice()
    ram = nildim > 0
    A = O.algebra_mod_ell()
    dec = sorted(A.residue_decomposition())
    out.update({"method": out.get("method", "Round 2"), "Z[alpha]_ell_maximal": False,
                "round2_iterations": iterations, "index_valuation": t,
                "v_disc_O": v - 2 * t, "ramified": ram,
                "ell_maximal_order_basis": [[str(x) for x in row] for row in O.B],
                "radical_nilpotent_dimension": nildim,
                "residue_decomposition": dec})
    assert (v - 2 * t == 0) == (not ram), "discriminant valuation is zero exactly when the prime is unramified"
    assert sum(e * f for e, f in dec) == K.n
    return out


def ramified_primes(f):
    """Full the procedure. f: ascending integer coefficients, monic, separable."""
    factors = factor_over_Z(f)
    discs = [discriminant(fi) for fi in factors]
    disc_f = discriminant(f)
    fact = [dict(sorted(factorint(abs(d)).items())) for d in discs]
    candidates = sorted({ell for fa in fact for ell in fa})
    per_prime = {}
    ramified = []
    for ell in candidates:
        rec = {"factors": {}}
        ram = False
        for i, fi in enumerate(factors):
            if discs[i] % ell:
                continue
            w = decide_prime_for_factor(fi, ell)
            rec["factors"][str(i)] = w
            ram = ram or w["ramified"]
        rec["ramified"] = ram
        rec["v_disc_f"] = valuation(disc_f, ell)
        rec["v_disc_O_A"] = sum(w["v_disc_O"] for w in rec["factors"].values())
        per_prime[ell] = rec
        if ram:
            ramified.append(ell)
    return {"factors": factors, "disc_factors": discs, "disc_f": disc_f,
            "disc_factorizations": [{str(k): v for k, v in fa.items()} for fa in fact],
            "candidates": candidates, "ramified": ramified,
            "per_prime": {str(ell): rec for ell, rec in per_prime.items()}}


# ------------------------------------------------------------ verifier (the verifier specification V0(f))

def verify_witness(fi, ell, w):
    """Recompute the verdict of decide_prime_for_factor from its witness.
    Returns (ok, message)."""
    v = valuation(discriminant(fi), ell)
    if w.get("v_disc_f") != v:
        return False, "v_ell(disc f_i) mismatch"
    if w["method"] == "odd valuation":
        return (v % 2 == 1 and w["ramified"]), "odd valuation"
    if w["method"] == "Dedekind criterion":
        maximal, facs, gcds = dedekind_criterion(fi, ell)
        if not maximal:
            return False, "Z[alpha] is not ell-maximal"
        ram = any(e >= 2 for _, e in facs)
        return (ram == w["ramified"] and w["v_disc_O"] == v), "Dedekind criterion recomputed"
    if w["method"] == "Round 2":
        K = NumberFieldPower(fi)
        B = [[Fraction(x) for x in row] for row in w["ell_maximal_order_basis"]]
        O = OrderAtPrime(K, ell, B)
        # contains Z[alpha]
        for i in range(K.n):
            co = vec_mat([Fraction(1 if j == i else 0) for j in range(K.n)], O.Binv)
            if any(c.denominator != 1 for c in co):
                return False, "recorded order does not contain Z[alpha]"
        try:
            O.structure_constants()
        except AssertionError:
            return False, "recorded basis is not closed under multiplication"
        t = O.index_valuation()
        if t != w["index_valuation"] or v - 2 * t != w["v_disc_O"]:
            return False, "index valuation mismatch"
        Onew, same, nildim = O.multiplier_ring()
        if not same:
            return False, "recorded order is not ell-maximal (multiplier ring is larger)"
        if (nildim > 0) != w["ramified"]:
            return False, "radical test disagrees with recorded verdict"
        dec = sorted(O.algebra_mod_ell().residue_decomposition())
        if dec != [tuple(x) for x in w["residue_decomposition"]]:
            return False, "residue decomposition mismatch"
        return True, "Round 2 witness recomputed"
    return False, "unknown method"


def verify_ramified(R):
    """Verify every witness in the output of ramified_primes; returns (ok, list of messages)."""
    ok = True
    msgs = []
    factors = R["factors"]
    for ell_s, rec in R["per_prime"].items():
        ell = int(ell_s)
        ram = False
        for i_s, w in rec["factors"].items():
            good, msg = verify_witness(factors[int(i_s)], ell, w)
            ok = ok and good
            msgs.append(f"ell={ell} factor {i_s}: {msg} ({'ok' if good else 'FAIL'})")
            ram = ram or w["ramified"]
        if ram != rec["ramified"] or (ram != (ell in R["ramified"])):
            ok = False
            msgs.append(f"ell={ell}: aggregated verdict inconsistent")
    return ok, msgs